sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node-test .
  - docker images mannydesigns/node-test

before_deploy:
  - docker login -u mannydesigns  -p vVc9xAvUZK81whlk

deploy:
  provider: script
  script: docker push mannydesigns/node-test
  on:
    branch: master