sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node-test .
  - docker images mannydesigns/node-test

before_deploy:
  - docker login -u <username>  -p <userpassword>

deploy:
  provider: script
  script: docker push mannydesigns/node-test
  on:
    branch: master